nelmio_security:
    # prevents framing of the entire site
    #clickjacking:
    #    paths:
    #        '^/.*': DENY

    # disables content type sniffing for script resources
    #content_type:
    #    nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    #xss_protection:
    #    enabled: true
    #    mode_block: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    #referrer_policy:
    #    enabled: true
    #    policies:
    #        - 'no-referrer'
    #        - 'strict-origin-when-cross-origin'

    csp:
        hash:
            algorithm: sha384
        hosts: []
        content_types: []
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false

            default-src: ['none']
            base-uri: ['none']
            object-src: ['none']
            frame-ancestors: ['none']
            # using 'strict-dynamic' is potentially less secure but break less preview embeds
            # must be used with nonce or hash
            #script-src: ['self', 'unsafe-inline', 'https:', 'strict-dynamic']
            script-src: ['self']
            style-src: ['self', 'unsafe-inline']
            connect-src: ['self']
            manifest-src: ['self']
            img-src: ['self', 'https:', 'data:']
            media-src: ['self', 'https:']
            font-src: ['self']
            frame-src: ['self', 'https:']
            form-action: ['self']
            #sandbox: ['allow-scripts']
            block-all-mixed-content: true
            upgrade-insecure-requests: true
