# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
  adapters:
    default_adapter:
      local:
        location: "%kernel.project_dir%/public/%uploads_dir_name%"

    kbin.s3_adapter:
      awss3v3:
        client: kbin.s3_client
        bucket: "%amazon.s3.bucket%"
        #options:
        #  ACL: public-read

        # If using an s3 bucket with owner-full-control and no ACL, the following may work:
        #options:
        #  ACL: ''

    # this is used to mainly get /emoji path prefix
    mbin.emoji_adapter:
      #local:
      #  location: "%kernel.project_dir%/public/%uploads_dir_name%/emoji"
      awss3v3:
        client: kbin.s3_client
        bucket: "%amazon.s3.bucket%"
        prefix: 'emoji'

  filesystems:
    public_uploads_filesystem:
      #adapter: default_adapter
      adapter: kbin.s3_adapter
      alias: League\Flysystem\Filesystem

    emoji:
      adapter: mbin.emoji_adapter
      visibility: public
