magazine_style:
  controller: App\Controller\CustomStyleController::magazineCustomStyle
  path: /customstyle/m/{name}.css
  methods: [ GET ]
  stateless: true
  requirements:
    name: '[^/]+'

user_style:
  controller: App\Controller\CustomStyleController::userCustomStyle
  path: /customstyle/user.css
  methods: [ GET ]
  stateless: true
